server:
  port: 8888

spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: file:///Users/yong/project/study/spring-boot-microservice/git-localconfig-repo

logging:
  level:
    org:
      springframework: INFO